//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje7MVC.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abouts
    {
        public int AboutId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Point1 { get; set; }
        public string Point2 { get; set; }
        public string Point3 { get; set; }
        public string InsurancePolicies { get; set; }
        public string SkilledAgents { get; set; }
        public string AwardsWON { get; set; }
        public string TeamMembers { get; set; }
    }
}
