//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje7MVC.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROJE7MVCEntities1 : DbContext
    {
        public PROJE7MVCEntities1()
            : base("name=PROJE7MVCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abouts> Abouts { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Faqs> Faqs { get; set; }
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }
        public virtual DbSet<Testimonials> Testimonials { get; set; }
    }
}
